### ISSUE TITLE
Add support to 'abstention' 

### ISSUE THREAD

**Issue by lock9** [AxLabs/grantshares#13]
Hi,

## Problem
I have a relationship with both COZ and NNT. If they don't vote for my proposal (just skip the voting), my proposal will never be accepted. 

## Proposed solutions:
- Add abstain feature. Allow a vote to be cast as neutral. This will reduce the number of votes required to approve it.
- Allow vote to weight to be configurable. COZ and NNT could cast a vote with 0 weight. This would show participation, demonstrate their intent to support it, and at the same time, avoid influencing directly on the results.

I don't know exactly what the rules are, who can vote, when, and how.

**Comment by gsmachado** [comment]
In short: GrantShares dApp already has support for casting "abstain" votes. 

It's live since the first version and explanation about it is available on the docs page as well.

**Comment by gsmachado** [comment]
Thus, I will close this issue.

Feel free to re-open if you think we should add anything else.
