### ISSUE TITLE
Add docs link to the header

### ISSUE THREAD

**Issue by lock9** [AxLabs/grantshares#14]
Hi,

Problem: It is hard to see the link for the docs from the home page.
Proposed solution: Add the link to the header
![image](https://user-images.githubusercontent.com/38396062/178604704-c15c4ffc-3f38-49af-a1f0-53f03755290f.png)

**Comment by gsmachado** [comment]
Thanks for pointing it out!

We'll consider including on the header.👍

As a side note, we already have the docs link on the footer. 😅

**Comment by lock9** [comment]
I've only noticed it because you said it on the other issue. I didn't know that these docs existed!

**Comment by gsmachado** [comment]
@csmuller what's your opinion on this?

**Comment by csmuller** [comment]
I think @lock9 is right. Putting it in the menu makes sense. We'll track this change in the frontend repository which is private ATM. Closing this one. Thanks @lock9 for the feedback.
