### ISSUE TITLE



Talking about Neo 💚🚀

### ISSUE THREAD

**Issue by josuhannymendez** [AxLabs/grantshares#30]
**Proposal** 
I am the Community Manager of the official group of the Neo telegram group in Spanish

_**This is my proposal:**_
Hold a face-to-face event in Spanish in the center of the city (Venezuela🇻🇪), in order to attract the Spanish-speaking public to the event where several series of presentations will be presented, with the following topics:

📍What is neo? 
📍Main features of Neo. 
📍The Neo token and gas
dual tokens. 
📍Neo’s technology.
📍Eco Support.

These will be interactive presentations, where any participant can ask a question.

**Name of the event:** Talking about Neo 
Event date: It will be defined as soon as the proposal is approved 

**Place of the event:** 
Eurocaribe / Carúpano-Sucre 

**Event venue link: ** https://g.co/kgs/EkniZU 

**Event coordinator/contact person:  **
Gmail: josuhannymendez@gmail.com
Telegram: @josumendez

📍**Target audience – who
Which group(s) is the event targeted attendee?**
Our target audience would be:
Men and women aged 20-50, upper middle class, with great interest in cryptocurrencies and their technologies

**What does the audience need/want to know?**
Traders in the area want to invest lately but they don’t know what, so we must let them know that Neo is an opportunity

**What will hold their interest?**
What will keep your interest is that in the city there is little information about cryptocurrencies and people have always been interested in their technologies and also want to use them in their daily lives.

📍**Message – what**
What do you want to say to the target audience?
What do you want them to know/do?

What I want our public to know is:
What is neo?
Main features of Neo 
The Neo token and gas dual tokens 
Neo’s technology
Eco Support
(I want them to learn about Neo and they can also invest)

📍**Objectives – why**
Be clear about what you hope to achieve with this event – actionable & measurable
My goal is for 150 people to attend the event
(And that each 1 of them can learn the most about Neo)

📍**Risk assessment – what**
Identify possible risks and develop strategies to minimise risks
Some risks are that people do not know how to invest
The strategy would be:
Have a small group of Moderators to help people in any situation.
(invest, find the white paper, etc.)

Before, it was a risk that the pre-established number of participants did not attend
*But after analyzing it, it will not be a risk, since without advertising or marketing, just mentioning it to colleagues in the city who have interests in cryptocurrencies, about 70 said that they would love to attend an event of this type
I will make sure that enough people come anyway, because at the 120-150 that will be invited I will ask them to confirm if they will attend in a Google form.
Also, I will make sure that the ad campaigns have the right effect and I will personally invite some people who are also from the crypto community.

Evaluation criteria established
What were our aims/objectives?
Did we achieve what we set out to do?
Did it come in on budget?
What were the intended/unintended outcomes?
How do we measure effectiveness?
What tools do we use to measure our success?
(All this will be answered after the event)

**Checklist**✅
1 Who will be involved in organizing the event  (Done)
2 Date/s of event determined  (Done)
3 Location/venue for event booked.  (Done)
4 Target audience determined . (Done)
5 Message determined.  (Done)
6 Objectives set.  (Done)
7 Risk assessment completed.  (Done)
8 Evaluation criteria established.  (Done)

**Early event planning**
Develop proposed program
**Topics**
📍What is neo?
📍Main features of Neo. 
📍The Neo token and gas dual tokens .
📍Neo’s technology.
📍Eco Support.

**Potential leaders / speakers
Speakers:**
Mickey Olivier (In charge of part of the presentation of the topics 

**Neo representatives:**

_Josuhanny Mendez _ (Responsible for the supervision, organization of the event and responsible for answering questions during the presentation)

_Souhayla Jallet  _(List to answer questions )

_Haine Cahmseddin. _(Answer questions and maintain team management)

📍**Budget**
Funding sources identified:
Neo 
Sponsorship
No
Create budget projections:
 11,360$ 

Venue Selection
 Create event specification and facility needs
Person in charge: Assembly staff and audio manager
Needs of the facilities: lighting, assembly, cleaning, ssound

📍**Registration Management**
Determine tool or method:
Binance 
Payment acceptance:
National currency of the country (Bs)
( this case I can accept Neo and change them myself to the currency of my country)

Exhibitor and Patron Plans
Marketing program

Person in charge: Josuhanny Mendez and Mickey Olivier

📍**(Objetives ) **
New Spanish-speaking investors, grow the Hispanic community in all social networks

📍**( Marketing )** 
Advertising will be carried out on the influencer’s social networks and advertising campaigns will also be carried out with Ads 
In addition to sharing advertising in:

**Links:**
https://t.me/CryptoLegacyEN
https://t.me/CazadoresDeTokens
https://t.me/NFTGAMING_CRYPTOS
And their respective twitters 

The marketing will start 1 month before the event for greater reach, (which means that the marketing payment will also be needed for 1 month before)

📍Program Planning

**Speakers**
Identify several speaker candidates
Person in charge ; Mickey Olivier 
He will be responsible for explaining and presenting the topics 

📍**Invitations**
Person in charge ; Josuhanny Mendez / Haine Cahmseddin
Will send them by email and will ensure that the guests confirm their attendance
Invitations will be sent 4 days before the event 

📍**Targeted attendee list
Person in charge:**
Josuhany Mendez 
Haine Cahmseddin

Past attendee/ prospect list generated/updated
    Invitation composed
    Invitation checked
    Invitations sent
Generate list of attendees 2 week before the event
Create invitation 1 week before the event
Send invitations 4 days before the event

📍**Signage/Printed Materials
Persona un charge :**
Printed and advertising material, place it in visible points
It will be placed on the day of the preparation of the premises (day of the event in the morning)

📍**Value added for guests**
    Gifts
   Catalogues
   Prizes

📍**Person in charge; Gerald
Graphic design:**
*Informative leaflets
*Schedule program 
*Banner for photos
*Welcome Banner
*Flyers for social networks

📍**Prizes:**
$500 to draw in Neo token

Previous contest 1 week before the event:
📍
**Contest with templates **
Something like :
Like and rt this post
And make a comment with the hashtag #NeoEvent
(every day we can make a different template)

And send your proof to the shill group.
By proof I mean a screenshot
(we will create a group of neo shill, so that users can send their tests and thus the main group is not overloaded)
And only the first 30 people who send their capture will be numbered

We list the screenshots, and finally we will activate the bot at that moment so that it chooses the number randomly.
In addition, a bot will be configured to tell users that they have successfully submitted entries. That way, users can make sure they're doing it successfully, and the other watchers will see and want to join too.

I was thinking we could do it once a day since the event banners are up
With a $10 gas prize.

📍**Space planning**
    Furniture/other needs

**Person in charge**: Daniel gamardo
Tables and chair, will be rented

Food and beverage (F&B)
    Service style
    Menu choices
    Special dietary requirements of guests

📍**Catering service**:
Soft drinks, juices and mineral water will be offered
Snacks and cake shots there will also be a menu for some celiac people who will attend the event

📍**Audio/visual requirements**
 Video beam
 Lapel or handheld microphone
 illumination
**Person in charge:** audio and video equipment
All equipment will be prepared and tested in advance

📍**Moderators for additional tasks:**
Sujhainnys gutierres
Daniela gamardo
Joshua Gómez 
They will take care of making the guests feel comfortable and talk to them a little about nne
They will be prepared in advance so that they know what they should 

📍**Ambience**:
 Background music
Person in charge: Audio and video equipment
Background music will be played, not too loud to relax the atmosphere

📍**Hospitality**:
 Welcome signage at entrance
will take care of putting it at the entrance in a visible way

📍**Housekeeping**
Responsible person: cleaning team
    Cleaning before and after
    On standby during the event
It will take place after the end of the event.

📍**After the event
 Debrief**
Josuhanny Mendez will make a report on the negative and positive aspects of the event

📍**Thank You’s – Exhibitors/Patrons,** Volunteers, speakers    and committee
The representatives will make the acknowledgments 

📍**Celebration** ✅

**Detailed budget:**

📍**Conference room rental (Eurocaribe) **$800
Link:
https://instagram.com/eurocaribehotel?igshid=YmMyMTA2M2Y=

📍**Audio and video service:**
Video beam, Lighting, Amplifiers and microphones 350$

📍**Venue decoration**: $380

📍**Photographer for the event: **$250

📍**Invited influencer and advertising on their networks:** $750 (Mickey Olivier)

📍*Advertising from 1 month before the event:
Advertising campaign in:**
Instagram Ads: $450
Facebook Ads: $450
CryptoLegacyES: $750
Chip Hunters $350
NftGaming : $350

📍**Pop material:
Printing of banners, program, triptychs and banner for photos :**
:1000$

📍**Catering service:**600$
(Snacks,Beverages )

📍**Uniform for the 3 Neo Representatives and the 3 Moderators :** 400$

📍**Draw among the participants:**
$500 in Neo for 10 winners

📍**Contest with templates** 250$

📍**Security service for interiors and the entrance: **150$
**Transportation for the team:** 180$

📍**Staff** :
Neo representatives:
Souhayla Jallet 250$
Haine Cahmseddin 250$
Josuhanny Mendez 450$

📍**Moderators:**
Sujhainnys gutierres 150$
Daniela gamardo 150$
Joshua Gómez 150$

📍Volunteers:
Fabiana Aguilar 0
Genadio Montaño 0

📍Graphic designer : 2000$

📍Celebración ; ¿?
Tips :100$

**Total** : 11,360$

**Comment by josuhannymendez** [comment]
> **Proposal** 
> I am the Community Manager of the official group of the Neo telegram group in Spanish
> 
> _**This is my proposal:**_
> Hold a face-to-face event in Spanish in the center of the city (Venezuela🇻🇪), in order to attract the Spanish-speaking public to the event where several series of presentations will be presented, with the following topics:
> 
> 📍What is neo? 
> 📍Main features of Neo. 
> 📍The Neo token and gas
> dual tokens. 
> 📍Neo’s technology.
> 📍Eco Support.
> 
> These will be interactive presentations, where any participant can ask a question.
> 
> 
> **Name of the event:** Talking about Neo 
> Event date: It will be defined as soon as the proposal is approved 
> 
> **Place of the event:** 
> Eurocaribe / Carúpano-Sucre 
> 
> **Event venue link: ** https://g.co/kgs/EkniZU 
> 
> **Event coordinator/contact person:  **
> Gmail: josuhannymendez@gmail.com
> Telegram: @josumendez
> 
> 
> 📍**Target audience – who
> Which group(s) is the event targeted attendee?**
> Our target audience would be:
> Men and women aged 20-50, upper middle class, with great interest in cryptocurrencies and their technologies
> 
> **What does the audience need/want to know?**
> Traders in the area want to invest lately but they don’t know what, so we must let them know that Neo is an opportunity
> 
> **What will hold their interest?**
> What will keep your interest is that in the city there is little information about cryptocurrencies and people have always been interested in their technologies and also want to use them in their daily lives.
> 
> 📍**Message – what**
> What do you want to say to the target audience?
> What do you want them to know/do?
> 
> What I want our public to know is:
> What is neo?
> Main features of Neo 
> The Neo token and gas dual tokens 
> Neo’s technology
> Eco Support
> (I want them to learn about Neo and they can also invest)
> 
> 📍**Objectives – why**
> Be clear about what you hope to achieve with this event – actionable & measurable
> My goal is for 150 people to attend the event
> (And that each 1 of them can learn the most about Neo)
> 
> 
> 📍**Risk assessment – what**
> Identify possible risks and develop strategies to minimise risks
> Some risks are that people do not know how to invest
> The strategy would be:
> Have a small group of Moderators to help people in any situation.
> (invest, find the white paper, etc.)
> 
> Before, it was a risk that the pre-established number of participants did not attend
> *But after analyzing it, it will not be a risk, since without advertising or marketing, just mentioning it to colleagues in the city who have interests in cryptocurrencies, about 70 said that they would love to attend an event of this type
> I will make sure that enough people come anyway, because at the 120-150 that will be invited I will ask them to confirm if they will attend in a Google form.
> Also, I will make sure that the ad campaigns have the right effect and I will personally invite some people who are also from the crypto community.
> 
> Evaluation criteria established
> What were our aims/objectives?
> Did we achieve what we set out to do?
> Did it come in on budget?
> What were the intended/unintended outcomes?
> How do we measure effectiveness?
> What tools do we use to measure our success?
> (All this will be answered after the event)
> 
> **Checklist**✅
> 1 Who will be involved in organizing the event  (Done)
> 2 Date/s of event determined  (Done)
> 3 Location/venue for event booked.  (Done)
> 4 Target audience determined . (Done)
> 5 Message determined.  (Done)
> 6 Objectives set.  (Done)
> 7 Risk assessment completed.  (Done)
> 8 Evaluation criteria established.  (Done)
> 
> 
> 
> **Early event planning**
> Develop proposed program
> **Topics**
> 📍What is neo?
> 📍Main features of Neo. 
> 📍The Neo token and gas dual tokens .
> 📍Neo’s technology.
> 📍Eco Support.
> 
> **Potential leaders / speakers
> Speakers:**
> Mickey Olivier (In charge of part of the presentation of the topics 
> 
> **Neo representatives:**
> 
> _Josuhanny Mendez _ (Responsible for the supervision, organization of the event and responsible for answering questions during the presentation)
> 
> _Souhayla Jallet  _(List to answer questions )
> 
> _Haine Cahmseddin. _(Answer questions and maintain team management)
> 
> 📍**Budget**
> Funding sources identified:
> Neo 
> Sponsorship
> No
> Create budget projections:
>  11,360$ 
> 
> Venue Selection
>  Create event specification and facility needs
> Person in charge: Assembly staff and audio manager
> Needs of the facilities: lighting, assembly, cleaning, ssound
> 
> 
> 📍**Registration Management**
> Determine tool or method:
> Binance 
> Payment acceptance:
> National currency of the country (Bs)
> ( this case I can accept Neo and change them myself to the currency of my country)
> 
> Exhibitor and Patron Plans
> Marketing program
> 
> Person in charge: Josuhanny Mendez and Mickey Olivier
> 
> 📍**(Objetives ) **
> New Spanish-speaking investors, grow the Hispanic community in all social networks
> 
> 📍**( Marketing )** 
> Advertising will be carried out on the influencer’s social networks and advertising campaigns will also be carried out with Ads 
> In addition to sharing advertising in:
> 
> **Links:**
> https://t.me/CryptoLegacyEN
> https://t.me/CazadoresDeTokens
> https://t.me/NFTGAMING_CRYPTOS
> And their respective twitters 
> 
> The marketing will start 1 month before the event for greater reach, (which means that the marketing payment will also be needed for 1 month before)
> 
> 
> 📍Program Planning
> 
> **Speakers**
> Identify several speaker candidates
> Person in charge ; Mickey Olivier 
> He will be responsible for explaining and presenting the topics 
> 
> 📍**Invitations**
> Person in charge ; Josuhanny Mendez / Haine Cahmseddin
> Will send them by email and will ensure that the guests confirm their attendance
> Invitations will be sent 4 days before the event 
> 
> 📍**Targeted attendee list
> Person in charge:**
> Josuhany Mendez 
> Haine Cahmseddin
> 
> Past attendee/ prospect list generated/updated
>     Invitation composed
>     Invitation checked
>     Invitations sent
> Generate list of attendees 2 week before the event
> Create invitation 1 week before the event
> Send invitations 4 days before the event
> 
> 📍**Signage/Printed Materials
> Persona un charge :**
> Printed and advertising material, place it in visible points
> It will be placed on the day of the preparation of the premises (day of the event in the morning)
> 
> 
> 📍**Value added for guests**
>     Gifts
>    Catalogues
>    Prizes
> 
> 📍**Person in charge; Gerald
> Graphic design:**
> *Informative leaflets
> *Schedule program 
> *Banner for photos
> *Welcome Banner
> *Flyers for social networks
> 
> 
> 📍**Prizes:**
> $500 to draw in Neo token
> 
> Previous contest 1 week before the event:
> 📍
> **Contest with templates **
> Something like :
> Like and rt this post
> And make a comment with the hashtag #NeoEvent
> (every day we can make a different template)
> 
> And send your proof to the shill group.
> By proof I mean a screenshot
> (we will create a group of neo shill, so that users can send their tests and thus the main group is not overloaded)
> And only the first 30 people who send their capture will be numbered
> 
> We list the screenshots, and finally we will activate the bot at that moment so that it chooses the number randomly.
> In addition, a bot will be configured to tell users that they have successfully submitted entries. That way, users can make sure they're doing it successfully, and the other watchers will see and want to join too.
> 
> I was thinking we could do it once a day since the event banners are up
> With a $10 gas prize.
> 
> 📍**Space planning**
>     Furniture/other needs
> 
> **Person in charge**: Daniel gamardo
> Tables and chair, will be rented
> 
> Food and beverage (F&B)
>     Service style
>     Menu choices
>     Special dietary requirements of guests
> 
> 📍**Catering service**:
> Soft drinks, juices and mineral water will be offered
> Snacks and cake shots there will also be a menu for some celiac people who will attend the event
> 
> 📍**Audio/visual requirements**
>  Video beam
>  Lapel or handheld microphone
>  illumination
> **Person in charge:** audio and video equipment
> All equipment will be prepared and tested in advance
> 
> 
> 📍**Moderators for additional tasks:**
> Sujhainnys gutierres
> Daniela gamardo
> Joshua Gómez 
> They will take care of making the guests feel comfortable and talk to them a little about nne
> They will be prepared in advance so that they know what they should 
> 
> 📍**Ambience**:
>  Background music
> Person in charge: Audio and video equipment
> Background music will be played, not too loud to relax the atmosphere
> 
> 📍**Hospitality**:
>  Welcome signage at entrance
> will take care of putting it at the entrance in a visible way
> 
> 📍**Housekeeping**
> Responsible person: cleaning team
>     Cleaning before and after
>     On standby during the event
> It will take place after the end of the event.
> 
> 📍**After the event
>  Debrief**
> Josuhanny Mendez will make a report on the negative and positive aspects of the event
> 
> 📍**Thank You’s – Exhibitors/Patrons,** Volunteers, speakers    and committee
> The representatives will make the acknowledgments 
> 
> 📍**Celebration** ✅
> 
> **Detailed budget:**
> 
> 📍**Conference room rental (Eurocaribe) **$800
> Link:
> https://instagram.com/eurocaribehotel?igshid=YmMyMTA2M2Y=
> 
> 📍**Audio and video service:**
> Video beam, Lighting, Amplifiers and microphones 350$
> 
> 📍**Venue decoration**: $380
> 
> 📍**Photographer for the event: **$250
> 
> 📍**Invited influencer and advertising on their networks:** $750 (Mickey Olivier)
> 
> 📍*Advertising from 1 month before the event:
> Advertising campaign in:**
> Instagram Ads: $450
> Facebook Ads: $450
> CryptoLegacyES: $750
> Chip Hunters $350
> NftGaming : $350
> 
> 
> 
> 📍**Pop material:
> Printing of banners, program, triptychs and banner for photos :**
> :1000$
> 
> 📍**Catering service:**600$
> (Snacks,Beverages )
> 
> 📍**Uniform for the 3 Neo Representatives and the 3 Moderators :** 400$
> 
> 📍**Draw among the participants:**
> $500 in Neo for 10 winners
> 
> 📍**Contest with templates** 250$
> 
> 📍**Security service for interiors and the entrance: **150$
> **Transportation for the team:** 180$
> 
> 
> 📍**Staff** :
> Neo representatives:
> Souhayla Jallet 250$
> Haine Cahmseddin 250$
> Josuhanny Mendez 450$
> 
> 📍**Moderators:**
> Sujhainnys gutierres 150$
> Daniela gamardo 150$
> Joshua Gómez 150$
> 
> 📍Volunteers:
> Fabiana Aguilar 0
> Genadio Montaño 0
> 
> 📍Graphic designer : 2000$
> 
> 📍Celebración ; ¿?
> Tips :100$
> 
> **Total** : 11,360$
> 
Address Neo N3: NdB37YWKaiyV7SFFAWYzNmoHjvmeUufJuS

> 
> 
> 
> 
> 
> 
>

**Comment by josuhannymendez** [comment]
Adress Neo N3:
NdB37YWKaiyV7SFFAWYzNmoHjvmeUufJuS
Gmail binance : josuhannymendez@gmail.com

**Comment by TusMey2099** [comment]
💯

**Comment by Fernandogiller** [comment]
Finally something is Spanish. 
This will be great...

**Comment by gsmachado** [comment]
Unfortunately, this proposal was not submitted through the GrantShares dApp and will be closed without further consideration.

Please go to https://grantshares.io, click on "Launch App", and then "Create a Proposal". Use the template and adapt with the content submitted in this issue.

Thanks for your understanding.
