### ISSUE TITLE
Talking about Neo 

### ISSUE THREAD

**Issue by josuhannymendez** [AxLabs/grantshares#31]

**Comment by gsmachado** [comment]
Hello @josuhannymendez 

I think you didn't understand. But let me post here one more time:

Unfortunately, this proposal WAS NOT submitted through the [GrantShares dApp](https://grantshares.io) and will be closed without further consideration.

Please go to https://grantshares.io, click on "Launch App", and then "Create a Proposal". Use the template and adapt with the content submitted in this issue.

Thanks for your understanding.
