### ISSUE TITLE
Adding links to the form appends "https://github.com/AxLabs/grantshares/" before the link

### ISSUE THREAD

**Issue by robliou** [AxLabs/grantshares#49]
Hi! 

As the title explains, when adding links to the GrantShares form, "https://github.com/AxLabs/grantshares/" gets appended to any URL that is posted. For example, if I try to add the link: "www.espn.com" and submit the form, the link that is generated in the app directs to 
"https://github.com/AxLabs/grantshares/www.espn.com."

To get around this, I simply bypassed using the link feature and instead pasted the full name of the link. However, this obviously this isn't optimal. Anyways, not a breaking change or anything.

Thanks!

**Comment by gsmachado** [comment]
hey @robliou

Thanks for the issue! We'll check this asap!

**Comment by robliou** [comment]
Anytime! Let me know if I can help to fix it or anything else! @gsmachado

**Comment by csmuller** [comment]
Hey @robliou, we fixed the issue.
Thanks for pointing it out 🙏

**Comment by robliou** [comment]
> Hey @robliou, we fixed the issue. Thanks for pointing it out 🙏

Awesome!
